# Project: º¯Êý
# Makefile created by Red Panda C++ 2.25.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = º¯Êý_private.res
OBJ      = add.o º¯ÊýÓë¼òµ¥µÝ¹é.o $(RES)
LINKOBJ  = add.o º¯ÊýÓë¼òµ¥µÝ¹é.o º¯Êý_private.res
CLEANOBJ  =  add.o º¯ÊýÓë¼òµ¥µÝ¹é.o  º¯Êý_private.res º¯Êý.exe
LIBS     = 
INCS     =  
CXXINCS  =  
BIN      = º¯Êý.exe
CXXFLAGS = $(CXXINCS)  -g3 -pipe -Wall -D__DEBUG__
CFLAGS   = $(INCS)  -g3 -pipe -Wall -D__DEBUG__
RM       = del /q /f
WINDRESFLAGS  = 

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) > NUL 2>&1

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

add.o: add.c
	$(CC) -c add.c -o add.o $(CFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

º¯ÊýÓë¼òµ¥µÝ¹é.o: º¯ÊýÓë¼òµ¥µÝ¹é.c
	$(CC) -c º¯ÊýÓë¼òµ¥µÝ¹é.c -o º¯ÊýÓë¼òµ¥µÝ¹é.o $(CFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

º¯Êý_private.res: º¯Êý_private.rc 
	$(WINDRES) -i º¯Êý_private.rc --input-format=rc -o º¯Êý_private.res -O coff $(WINDRESFLAGS) 

